data_prep:
  dirs:
    Prompt: [training_samples/train_29283, training_samples/train_29284]
    Nonprompt: [training_samples/train_29283, training_samples/train_29284]
    Bkg: [training_samples/train_29282]
  channel: D0ToKPi  # options: D0ToKPi, DPlusToPiKPi, DsToKKPi, LcToPKPi, XicToPKPi
  preselection:
    enable: false # preselection possible only for Ds and baryons
    nsigma_tpc_proton: 3 # nsigma cut for proton
    nsigma_tof_proton: 3 # nsigma cut for proton
    delta_mass_kk: 0.020 # mass difference between KK and phi in GeV/c2
  class_balance:
    share: equal # options: equal, all_signal
    bkg_factor: 5 # factor to be applied to bkg sample compared to signal sample (only for share=all_signal)
  test_fraction: 0.3
  seed_split: 42

ml:
  raw_output: false
  roc_auc_approach: ovo
  roc_auc_average: macro
  training_vars: [fPT1, fDCAPrimXY1, fDCAPrimZ1, fPT2, fDCAPrimXY2, fDCAPrimZ2]
  hyper_pars: {'max_depth':4, 'learning_rate':0.01, 'n_estimators':1000, 'min_child_weight':5, 'n_jobs':4, 'tree_method':hist}
  hyper_pars_opt:
    activate: true
    ntrials: 25
    njobs: 4
    timeout: 1800
    hyper_par_ranges: {'max_depth': !!python/tuple [3, 6], 
                       'learning_rate': !!python/tuple [0.01, 0.1],
                       'n_estimators': !!python/tuple [300, 1500], 
                       'min_child_weight': !!python/tuple [1, 10],
                       'subsample': !!python/tuple [0.8, 1.], 
                       'colsample_bytree': !!python/tuple [0.8, 1.]}

output:
  directory: trainings/D0
