data_prep:
  dir: training_samples/train_14433
  channel: D0ToKPi  # options: D0ToKPi, DPlusToPiKPi, DsToKKPi, LcToPKPi, XicToPKPi
  test_fraction: 0.3
  seed_split: 42

ml:
  raw_output: false
  roc_auc_approach: ovo
  roc_auc_average: macro
  training_vars: [fDCAPrimXY1, fDCAPrimZ1, fDCAPrimXY2, fDCAPrimZ2]
  hyper_pars: {'max_depth':4, 'learning_rate':0.01, 'n_estimators':1000, 'min_child_weight':5, 'n_jobs':4, 'tree_method':hist}
  hyper_pars_opt:
    activate: true
    ntrials: 10
    njobs: 4
    timeout: 1800
    hyper_par_ranges: {'max_depth': !!python/tuple [3, 6], 
                       'learning_rate': !!python/tuple [0.01, 0.1],
                       'n_estimators': !!python/tuple [300, 1500], 
                       'min_child_weight': !!python/tuple [1, 10],
                       'subsample': !!python/tuple [0.8, 1.], 
                       'colsample_bytree': !!python/tuple [0.8, 1.]}

output:
  directory: trainings/D0
