infile:
    name: inputs/AnalysisResults_LHC18h4_CharmHadrons.root
    dir: PWGHF_D2H_CharmTrigger_GenPurpose

outfile:
    name: outputs/trigger/2ProngTrigger.root

cuts:
    2prong:
        ptmin: 0
